"""Validate full UI/story coverage and compile an exact binary-search catalog."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / 'assets/localization_en.json').read_text(encoding='utf-8'))
invariant = set(json.loads((ROOT / 'assets/localization_invariant.json').read_text(encoding='utf-8')))
tokens = re.compile(r'//[^\n]*|/\*[\s\S]*?\*/|"(?:\\.|[^"\\])*"')
specs = re.compile(r'%(?:[-+ #0\d.]*)([diuscfFgGxXoeE%])')
for es, en in catalog.items():
    assert en and en.isascii(), f'Unsupported English glyphs: {es}'
    assert specs.findall(es) == specs.findall(en), f'Changed format arguments: {es}'

missing = set()
for file in ('game.c', 'story.h', 'combat.inc', 'settings.inc', 'assets.h'):
    for match in tokens.finditer((ROOT / 'src' / file).read_text(encoding='utf-8')):
        token = match.group()
        if not token.startswith('"'):
            continue
        try:
            value = json.loads(token)
        except json.JSONDecodeError:
            continue
        if re.search('[A-Za-z]', value) and value not in catalog and value not in invariant:
            missing.add(value)
if missing:
    raise SystemExit('Untranslated strings:\n' + '\n'.join(sorted(missing)))

lines = ['/* Generated by tools/build_localization.py; do not edit manually. */',
         'typedef struct {const char *es,*en;} LocaleEntry;',
         'static const LocaleEntry localeCatalog[] = {']
for es in sorted(catalog, key=lambda s: s.encode('utf-8')):
    lines.append('    {' + json.dumps(es, ensure_ascii=False) + ',' + json.dumps(catalog[es]) + '},')
lines.append('};')
(ROOT / 'src/localization_catalog.h').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'PASS: {len(catalog)} translations; all UI, story, clues and notices covered; format arguments preserved.')
