"""Prepare full-resolution PSP title art and antialiased UI lettering."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps
import struct

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
cover = Image.open(ASSETS / "title-cover-v213.png").convert("RGB")
cards = Image.open(ASSETS / "title-cards-v213.png").convert("RGB")


def rgb565(image, name):
    image = image.convert("RGB")
    raw = bytearray()
    for r, g, b in image.getdata():
        raw += struct.pack("<H", (r >> 3) | ((g >> 2) << 5) | ((b >> 3) << 11))
    (ASSETS / name).write_bytes(raw)


rgb565(ImageOps.fit(cover, (480, 272), method=Image.Resampling.LANCZOS), "title-cover-v213.565")
background = ImageOps.fit(cover, (480, 272), method=Image.Resampling.LANCZOS).filter(
    ImageFilter.GaussianBlur(7)
)
background = Image.blend(background, Image.new("RGB", background.size, (5, 9, 20)), .70)
rgb565(background, "title-menu-v213.565")
for n, half in enumerate((cards.crop((0, 0, cards.width // 2, cards.height)),
                          cards.crop((cards.width // 2, 0, cards.width, cards.height)))):
    rgb565(ImageOps.fit(half, (208, 115), method=Image.Resampling.LANCZOS),
           f"title-card-{n}-v213.565")

fonts = Path("C:/Windows/Fonts")
font_regular = fonts / "segoeui.ttf"
font_bold = fonts / "segoeuib.ttf"
font_logo = fonts / "bahnschrift.ttf"
font_script = ROOT / "tools/Allura-Regular.ttf"
labels = [
    ("logo", "NARCADE", font_logo, 49),
    ("logo_small", "NARCADE", font_logo, 25),
    ("cover_sub", "MEDELLÍN  /  UNA HISTORIA ORIGINAL", font_regular, 12),
    ("press", "PULSA X O START", font_bold, 19),
    ("press_sub", "PARA COMENZAR", font_regular, 11),
    ("story", "HISTORIA", font_bold, 26),
    ("continue", "CONTINUAR PARTIDA", font_bold, 17),
    ("new", "NUEVA HISTORIA", font_bold, 17),
    ("continue_sub", "RETOMA TU AVENTURA", font_regular, 11),
    ("new_sub", "EMPIEZA EN MEDELLÍN", font_regular, 11),
    ("footer", "X SELECCIONAR    O VOLVER", font_regular, 12),
    ("credit", "Naresz", font_script, 27),
    ("made_by", "made by", font_regular, 10),
    ("story_kicker", "MUNDO ABIERTO  /  36 MISIONES", font_regular, 11),
]
data = bytearray()
records = []
for ident, label, face, size in labels:
    font = ImageFont.truetype(str(face), size)
    box = font.getbbox(label)
    width, height = box[2] - box[0] + 4, box[3] - box[1] + 4
    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((2 - box[0], 2 - box[1]), label, font=font, fill=255,
                                stroke_width=0)
    records.append((ident, len(data), width, height))
    data.extend(image.tobytes())
(ASSETS / "title-labels-v213.a8").write_bytes(data)
header = ["/* Generated by tools/build_title_ui.py. */",
          "#ifndef NARCADE_TITLE_UI_H", "#define NARCADE_TITLE_UI_H",
          "typedef struct { unsigned offset; unsigned short width,height; } TitleLabel;",
          "enum {" + ",".join("TL_" + name.upper() for name, *_ in records) + ", TL_COUNT };",
          "static const TitleLabel titleLabels[TL_COUNT] = {"]
header.extend(f"    {{{offset}u,{width},{height}}}, /* {name} */"
              for name, offset, width, height in records)
header += ["};", "#endif"]
(ROOT / "src/title_ui.h").write_text("\n".join(header) + "\n", encoding="ascii")
print("title art and typography:", len(data), "label alpha bytes")
