"""Original compact firearm illustrations, generated with no external assets."""
from PIL import Image, ImageDraw
from pathlib import Path
import random
random.seed(17)
names=['PUNOS','PISTOLA','REVOLVER','SUBFUSIL','AK','ESCOPETA','RIFLE','BATE']
icons=[]
for i in range(8):
 im=Image.new('RGBA',(128,64));d=ImageDraw.Draw(im)
 def part(box,kind='steel'):
  x0,y0,x1,y1=box
  palettes={'steel':(94,111,126),'dark':(42,49,59),'wood':(149,90,46),'skin':(184,131,94)}
  base=palettes[kind]
  d.rectangle(box,fill=(*base,255))
  for y in range(y0+1,y1):
   f=.65+.65*(1-(y-y0)/max(1,y1-y0))
   c=tuple(int(min(255,v*f)) for v in base)
   d.line((x0+1,y,x1-1,y),fill=(*c,255))
  d.line((x0,y0,x1,y0),fill=(185,196,200,255) if kind=='steel' else (*tuple(min(255,v+30) for v in base),255))
  if kind=='wood':
   for k in range(4):
    y=y0+2+k*max(2,(y1-y0)//4);d.line((x0+2,y,x1-2,y+1),fill=(93,55,27,255))
 if i==0:
  part((42,25,83,47),'skin')
  for k in range(4):part((42+k*10,14,50+k*10,32),'skin')
  part((80,33,92,44),'skin');d.line((46,37,75,37),fill=(126,78,49))
 elif i==7:
  d.line((22,48,100,17),fill=(70,39,25,255),width=12)
  d.line((49,36,105,14),fill=(172,111,58,255),width=12)
  d.line((51,33,105,11),fill=(212,158,93,255),width=3)
  for k in range(5):d.line((24+k*4,45-k*2,28+k*4,53-k*2),fill=(192,189,173,255),width=2)
 else:
  if i<3:
   part((29,22,96 if i==1 else 104,32));part((34,32,51,51),'dark')
   d.rounded_rectangle((49,31,70,43),radius=5,outline=(142,152,157,255),width=3)
   part((30,18,35,22),'dark');part((89,18,94,22),'dark')
   if i==2:d.ellipse((43,22,66,37),fill=(65,76,87),outline=(169,177,180),width=2)
   for k in range(4):d.line((34,35+k*4,47,34+k*4),fill=(92,98,99),width=2)
  else:
   wood=i in (4,5);part((10,29,34,42),'wood' if wood else 'dark');part((32,24,75,34))
   part((70,26,115,29),'dark');part((71,30,96,36),'wood' if wood else 'dark')
   part((37,34,47,51),'dark');d.rounded_rectangle((45,34,59,43),radius=3,outline=(143,153,155),width=2)
   if i in (3,4):
    d.polygon([(59,34),(71,34),(77,52),(66,55)],fill=(63,72,80),outline=(145,154,160))
    for k in range(3):d.line((62+k*3,38,69+k*3,50),fill=(103,111,117))
   if i==6:part((45,14,78,20),'dark');part((50,20,54,24));part((71,20,75,24))
   part((109,23,112,26),'steel')
   for k in range(4):d.line((53+k*4,26,53+k*4,30),fill=(32,39,46))
  d.line((96 if i<3 else 113,25,96 if i<3 else 113,29),fill=(13,18,23),width=2)
 im=im.resize((64,32),Image.Resampling.LANCZOS);icons.append(im)
out=Path('src/weapon_icons.h')
values=[]
for im in icons:
 for r,g,b,a in im.getdata():values.append(0 if a<80 else ((r>>3)|((g>>2)<<5)|((b>>3)<<11)) or 1)
out.write_text('/* Generated by tools/weapon_icons.py; original artwork. */\nstatic const unsigned short weapon_icons[8][2048]={\n'+',\n'.join('{'+','.join(map(str,values[i*2048:(i+1)*2048]))+'}' for i in range(8))+'\n};\n')
sheet=Image.new('RGB',(512,64),(16,28,36));draw=ImageDraw.Draw(sheet)
for i,im in enumerate(icons):sheet.paste(im,(i*64,0),im);draw.text((i*64+1,42),names[i],fill='white')
Path('build').mkdir(exist_ok=True);sheet.save('build/weapon_icons.png')
