/* Generated by tools/build_title_ui.py. */
#ifndef NARCADE_TITLE_UI_H
#define NARCADE_TITLE_UI_H
typedef struct { unsigned offset; unsigned short width,height; } TitleLabel;
enum {TL_LOGO,TL_LOGO_SMALL,TL_COVER_SUB,TL_PRESS,TL_PRESS_SUB,TL_STORY,TL_CONTINUE,TL_NEW,TL_CONTINUE_SUB,TL_NEW_SUB,TL_FOOTER,TL_CREDIT,TL_MADE_BY,TL_STORY_KICKER, TL_COUNT };
static const TitleLabel titleLabels[TL_COUNT] = {
    {0u,225,39}, /* logo */
    {8775u,116,22}, /* logo_small */
    {11327u,211,17}, /* cover_sub */
    {14914u,163,17}, /* press */
    {17685u,93,12}, /* press_sub */
    {18801u,126,22}, /* story */
    {21573u,182,16}, /* continue */
    {24485u,145,16}, /* new */
    {26805u,124,12}, /* continue_sub */
    {28293u,119,15}, /* new_sub */
    {30078u,155,13}, /* footer */
    {32093u,84,24}, /* credit */
    {34109u,43,13}, /* made_by */
    {34668u,173,14}, /* story_kicker */
};
#endif
